#!/bin/bash

export LIBRARY_PATH=$PREFIX/lib
export INCLUDE_PATH=$PREFIX/include

cmake \
    -DAQUAGPUSPH_3D=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPENCL_ROOT_DIR=/usr/lib/x86_64-linux-gnu \
    -DPYTHON_LIBRARIES=$LIBRARY_PATH \
    -DPYTHON_INCLUDE_DIRS=$INCLUDE_PATH \
    -DPYTHON_LIBRARY=$LIBRARY_PATH/libpython$PY_VER.so \
    -DPYTHON_INCLUDE_DIR=$INCLUDE_PATH/python$PY_VER \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DAQUAGPUSPH_USE_VTK:BOOL=OFF \
    -DAQUAGPUSPH_USE_NCURSES:BOOL=OFF \
    -DLLVM_LIBRARY=$LIBRARY_PATH/libLLVM-3.3.so \
    .
make
make install
